import { useState } from 'react';
import { useApi } from '../context/ApiContext';
import { generate } from '../services/api';
import { FileText, Download, Plus, Trash2, Eye, Zap, Loader2, Sparkles } from 'lucide-react';

interface InvoiceItem {
  id: number;
  description: string;
  quantity: number;
  price: number;
}

export default function InvoiceGenerator() {
  const { isConfigured } = useApi();
  const [invoice, setInvoice] = useState({
    number: `INV-${String(Math.floor(Math.random() * 900) + 100)}`,
    date: new Date().toISOString().split('T')[0],
    dueDate: '',
    fromName: '',
    fromEmail: '',
    fromAddress: '',
    toName: '',
    toEmail: '',
    toAddress: '',
    notes: '',
    currency: 'IDR',
  });

  const [items, setItems] = useState<InvoiceItem[]>([
    { id: 1, description: '', quantity: 1, price: 0 },
  ]);

  const [showPreview, setShowPreview] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);

  const addItem = () => {
    setItems([...items, { id: Date.now(), description: '', quantity: 1, price: 0 }]);
  };

  const removeItem = (id: number) => {
    setItems(items.filter(item => item.id !== id));
  };

  const updateItem = (id: number, field: keyof InvoiceItem, value: string | number) => {
    setItems(items.map(item => item.id === id ? { ...item, [field]: value } : item));
  };

  const subtotal = items.reduce((sum, item) => sum + (item.quantity * item.price), 0);
  const tax = subtotal * 0.11;
  const total = subtotal + tax;

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(amount);
  };

  // AI: Generate professional item descriptions
  const aiGenerateDescription = async (index: number) => {
    if (!isConfigured) return;
    setAiLoading(true);
    try {
      const result = await generate(
        `Buatkan deskripsi item invoice profesional dan detail (1 baris, max 80 karakter) untuk layanan freelance "${items[index].description || 'web development'}". Langsung berikan deskripsinya saja tanpa penjelasan tambahan.`,
        'Kamu adalah profesional yang menulis invoice. Buat deskripsi yang jelas, profesional, dan spesifik.'
      );
      updateItem(items[index].id, 'description', result.trim());
    } catch {}
    setAiLoading(false);
  };

  // AI: Generate notes/terms
  const aiGenerateNotes = async () => {
    if (!isConfigured) return;
    setAiLoading(true);
    try {
      const result = await generate(
        `Buatkan catatan profesional untuk invoice (payment terms, 2-3 kalimat). Langsung berikan teksnya saja.`,
        'Kamu menulis payment terms untuk invoice profesional.'
      );
      setInvoice({ ...invoice, notes: result.trim() });
    } catch {}
    setAiLoading(false);
  };

  const downloadInvoice = () => {
    const invoiceText = `
INVOICE
=======
Invoice #: ${invoice.number}
Date: ${invoice.date}
Due Date: ${invoice.dueDate}

FROM:
${invoice.fromName}
${invoice.fromEmail}
${invoice.fromAddress}

TO:
${invoice.toName}
${invoice.toEmail}
${invoice.toAddress}

ITEMS:
${items.map((item, i) => `${i + 1}. ${item.description} - ${item.quantity}x @ ${formatCurrency(item.price)} = ${formatCurrency(item.quantity * item.price)}`).join('\n')}

Subtotal: ${formatCurrency(subtotal)}
Tax (11%): ${formatCurrency(tax)}
TOTAL: ${formatCurrency(total)}

Notes: ${invoice.notes}

---
Generated by MoneyMaker Pro
    `.trim();

    const blob = new Blob([invoiceText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${invoice.number}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-5">
      {/* Action Buttons */}
      <div className="flex flex-wrap gap-2">
        <button onClick={() => setShowPreview(!showPreview)} className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 hover:bg-indigo-500/20 transition-all text-sm font-medium">
          <Eye className="w-4 h-4" />
          {showPreview ? 'Edit' : 'Preview'}
        </button>
        <button onClick={downloadInvoice} className="flex items-center gap-2 px-4 py-2.5 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-300 hover:bg-emerald-500/20 transition-all text-sm font-medium">
          <Download className="w-4 h-4" />
          Download Invoice
        </button>
        {isConfigured && (
          <div className="flex items-center gap-1.5 px-3 py-2 rounded-lg bg-purple-500/10 border border-purple-500/20 text-purple-300 text-xs font-medium">
            <Sparkles className="w-3.5 h-3.5" /> AI Enhanced
          </div>
        )}
      </div>

      {!showPreview ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
          {/* Invoice Details */}
          <div className="bg-slate-900/50 border border-slate-800/50 rounded-xl p-5 space-y-4">
            <h3 className="text-sm font-semibold text-white flex items-center gap-2">
              <FileText className="w-4 h-4 text-indigo-400" />
              Invoice Details
            </h3>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-xs text-slate-400 mb-1 block">Invoice #</label>
                <input type="text" value={invoice.number} onChange={e => setInvoice({...invoice, number: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
              </div>
              <div>
                <label className="text-xs text-slate-400 mb-1 block">Tanggal</label>
                <input type="date" value={invoice.date} onChange={e => setInvoice({...invoice, date: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
              </div>
              <div>
                <label className="text-xs text-slate-400 mb-1 block">Jatuh Tempo</label>
                <input type="date" value={invoice.dueDate} onChange={e => setInvoice({...invoice, dueDate: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
              </div>
              <div>
                <label className="text-xs text-slate-400 mb-1 block">Mata Uang</label>
                <select value={invoice.currency} onChange={e => setInvoice({...invoice, currency: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none">
                  <option value="IDR">IDR (Rupiah)</option>
                  <option value="USD">USD (Dollar)</option>
                  <option value="EUR">EUR (Euro)</option>
                </select>
              </div>
            </div>

            <div className="border-t border-slate-700 pt-4">
              <h4 className="text-sm font-medium text-slate-300 mb-3">Dari (Anda)</h4>
              <div className="space-y-2">
                <input type="text" placeholder="Nama Bisnis/Anda" value={invoice.fromName} onChange={e => setInvoice({...invoice, fromName: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                <input type="email" placeholder="Email" value={invoice.fromEmail} onChange={e => setInvoice({...invoice, fromEmail: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                <textarea placeholder="Alamat" value={invoice.fromAddress} onChange={e => setInvoice({...invoice, fromAddress: e.target.value})} rows={2}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600 resize-none" />
              </div>
            </div>

            <div className="border-t border-slate-700 pt-4">
              <h4 className="text-sm font-medium text-slate-300 mb-3">Kepada (Klien)</h4>
              <div className="space-y-2">
                <input type="text" placeholder="Nama Klien/Perusahaan" value={invoice.toName} onChange={e => setInvoice({...invoice, toName: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                <input type="email" placeholder="Email Klien" value={invoice.toEmail} onChange={e => setInvoice({...invoice, toEmail: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                <textarea placeholder="Alamat Klien" value={invoice.toAddress} onChange={e => setInvoice({...invoice, toAddress: e.target.value})} rows={2}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600 resize-none" />
              </div>
            </div>
          </div>

          {/* Items */}
          <div className="bg-slate-900/50 border border-slate-800/50 rounded-xl p-5 space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-semibold text-white">Invoice Items</h3>
              <button onClick={addItem} className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-xs font-medium hover:bg-indigo-500/20 transition-all">
                <Plus className="w-3.5 h-3.5" /> Add Item
              </button>
            </div>

            <div className="space-y-3">
              {items.map((item, index) => (
                <div key={item.id} className="p-3 rounded-lg bg-slate-800/30 border border-slate-800/50 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-slate-500">Item #{index + 1}</span>
                    <div className="flex items-center gap-2">
                      {isConfigured && (
                        <button onClick={() => aiGenerateDescription(index)} disabled={aiLoading}
                          className="flex items-center gap-1 text-xs text-purple-400 hover:text-purple-300 disabled:opacity-50">
                          {aiLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Zap className="w-3 h-3" />}
                          AI Desc
                        </button>
                      )}
                      {items.length > 1 && (
                        <button onClick={() => removeItem(item.id)} className="text-red-400 hover:text-red-300">
                          <Trash2 className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </div>
                  <input type="text" placeholder="Deskripsi layanan/produk" value={item.description}
                    onChange={e => updateItem(item.id, 'description', e.target.value)}
                    className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="text-xs text-slate-500">Qty</label>
                      <input type="number" min="1" value={item.quantity}
                        onChange={e => updateItem(item.id, 'quantity', parseInt(e.target.value) || 0)}
                        className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
                    </div>
                    <div>
                      <label className="text-xs text-slate-500">Harga</label>
                      <input type="number" min="0" value={item.price}
                        onChange={e => updateItem(item.id, 'price', parseInt(e.target.value) || 0)}
                        className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
                    </div>
                  </div>
                  <p className="text-xs text-emerald-400 font-medium">Total: {formatCurrency(item.quantity * item.price)}</p>
                </div>
              ))}
            </div>

            {/* Totals */}
            <div className="border-t border-slate-700 pt-4 space-y-2">
              <div className="flex justify-between text-sm text-slate-400">
                <span>Subtotal</span>
                <span>{formatCurrency(subtotal)}</span>
              </div>
              <div className="flex justify-between text-sm text-slate-400">
                <span>PPN (11%)</span>
                <span>{formatCurrency(tax)}</span>
              </div>
              <div className="flex justify-between text-lg font-bold text-white pt-2 border-t border-slate-700">
                <span>Total</span>
                <span className="text-emerald-400">{formatCurrency(total)}</span>
              </div>
            </div>

            {/* Notes */}
            <div>
              <div className="flex items-center justify-between mb-1">
                <label className="text-xs text-slate-400">Catatan / Payment Terms</label>
                {isConfigured && (
                  <button onClick={aiGenerateNotes} disabled={aiLoading}
                    className="flex items-center gap-1 text-xs text-purple-400 hover:text-purple-300 disabled:opacity-50">
                    {aiLoading ? <Loader2 className="w-3 h-3 animate-spin" /> : <Zap className="w-3 h-3" />}
                    AI Generate
                  </button>
                )}
              </div>
              <textarea placeholder="Catatan tambahan untuk klien..." value={invoice.notes} onChange={e => setInvoice({...invoice, notes: e.target.value})} rows={3}
                className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600 resize-none" />
            </div>
          </div>
        </div>
      ) : (
        /* Preview */
        <div className="bg-slate-900/50 border border-slate-800/50 rounded-xl p-6 max-w-3xl mx-auto">
          <div className="border-2 border-dashed border-slate-800 rounded-lg p-6">
            <div className="flex justify-between items-start mb-6">
              <div>
                <h2 className="text-xl font-bold gradient-text">INVOICE</h2>
                <p className="text-slate-500 text-xs mt-1">#{invoice.number}</p>
              </div>
              <div className="text-right">
                <p className="text-xs text-slate-500">Date: {invoice.date}</p>
                <p className="text-xs text-slate-500">Due: {invoice.dueDate || '-'}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-6 mb-6">
              <div>
                <h4 className="text-[10px] text-slate-600 uppercase tracking-wider mb-1.5">From</h4>
                <p className="text-sm text-white font-medium">{invoice.fromName || 'Your Name'}</p>
                <p className="text-xs text-slate-400">{invoice.fromEmail}</p>
                <p className="text-xs text-slate-400">{invoice.fromAddress}</p>
              </div>
              <div>
                <h4 className="text-[10px] text-slate-600 uppercase tracking-wider mb-1.5">To</h4>
                <p className="text-sm text-white font-medium">{invoice.toName || 'Client Name'}</p>
                <p className="text-xs text-slate-400">{invoice.toEmail}</p>
                <p className="text-xs text-slate-400">{invoice.toAddress}</p>
              </div>
            </div>

            <table className="w-full mb-6">
              <thead>
                <tr className="border-b border-slate-800">
                  <th className="text-left text-[10px] text-slate-600 py-2">DESCRIPTION</th>
                  <th className="text-center text-[10px] text-slate-600 py-2">QTY</th>
                  <th className="text-right text-[10px] text-slate-600 py-2">PRICE</th>
                  <th className="text-right text-[10px] text-slate-600 py-2">TOTAL</th>
                </tr>
              </thead>
              <tbody>
                {items.map(item => (
                  <tr key={item.id} className="border-b border-slate-800/50">
                    <td className="py-2.5 text-xs text-slate-300">{item.description || '-'}</td>
                    <td className="py-2.5 text-xs text-slate-400 text-center">{item.quantity}</td>
                    <td className="py-2.5 text-xs text-slate-400 text-right">{formatCurrency(item.price)}</td>
                    <td className="py-2.5 text-xs text-white text-right font-medium">{formatCurrency(item.quantity * item.price)}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            <div className="flex justify-end">
              <div className="w-56 space-y-1.5">
                <div className="flex justify-between text-xs text-slate-400">
                  <span>Subtotal</span>
                  <span>{formatCurrency(subtotal)}</span>
                </div>
                <div className="flex justify-between text-xs text-slate-400">
                  <span>Tax (11%)</span>
                  <span>{formatCurrency(tax)}</span>
                </div>
                <div className="flex justify-between text-sm font-bold text-white pt-1.5 border-t border-slate-800">
                  <span>Total</span>
                  <span className="text-emerald-400">{formatCurrency(total)}</span>
                </div>
              </div>
            </div>

            {invoice.notes && (
              <div className="mt-6 p-3 rounded-lg bg-slate-800/30 border border-slate-800/50">
                <p className="text-[10px] text-slate-600 mb-1">Notes:</p>
                <p className="text-xs text-slate-400">{invoice.notes}</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
