import { useState } from 'react';
import { FileText, Download, Plus, Trash2, Eye } from 'lucide-react';

interface InvoiceItem {
  id: number;
  description: string;
  quantity: number;
  price: number;
}

export default function InvoiceGenerator() {
  const [invoice, setInvoice] = useState({
    number: 'INV-001',
    date: new Date().toISOString().split('T')[0],
    dueDate: '',
    fromName: '',
    fromEmail: '',
    fromAddress: '',
    toName: '',
    toEmail: '',
    toAddress: '',
    notes: '',
    currency: 'IDR',
  });

  const [items, setItems] = useState<InvoiceItem[]>([
    { id: 1, description: '', quantity: 1, price: 0 },
  ]);

  const [showPreview, setShowPreview] = useState(false);

  const addItem = () => {
    setItems([...items, { id: Date.now(), description: '', quantity: 1, price: 0 }]);
  };

  const removeItem = (id: number) => {
    setItems(items.filter(item => item.id !== id));
  };

  const updateItem = (id: number, field: keyof InvoiceItem, value: string | number) => {
    setItems(items.map(item => item.id === id ? { ...item, [field]: value } : item));
  };

  const subtotal = items.reduce((sum, item) => sum + (item.quantity * item.price), 0);
  const tax = subtotal * 0.11;
  const total = subtotal + tax;

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(amount);
  };

  const downloadInvoice = () => {
    const invoiceText = `
INVOICE
=======
Invoice #: ${invoice.number}
Date: ${invoice.date}
Due Date: ${invoice.dueDate}

FROM:
${invoice.fromName}
${invoice.fromEmail}
${invoice.fromAddress}

TO:
${invoice.toName}
${invoice.toEmail}
${invoice.toAddress}

ITEMS:
${items.map((item, i) => `${i + 1}. ${item.description} - ${item.quantity}x @ ${formatCurrency(item.price)} = ${formatCurrency(item.quantity * item.price)}`).join('\n')}

Subtotal: ${formatCurrency(subtotal)}
Tax (11%): ${formatCurrency(tax)}
TOTAL: ${formatCurrency(total)}

Notes: ${invoice.notes}

---
Generated by MoneyMaker Pro
    `.trim();

    const blob = new Blob([invoiceText], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${invoice.number}.txt`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      {/* Action Buttons */}
      <div className="flex flex-wrap gap-3">
        <button onClick={() => setShowPreview(!showPreview)} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-indigo-500/20 border border-indigo-500/30 text-indigo-300 hover:bg-indigo-500/30 transition-all">
          <Eye className="w-4 h-4" />
          {showPreview ? 'Edit' : 'Preview'}
        </button>
        <button onClick={downloadInvoice} className="flex items-center gap-2 px-4 py-2 rounded-xl bg-emerald-500/20 border border-emerald-500/30 text-emerald-300 hover:bg-emerald-500/30 transition-all">
          <Download className="w-4 h-4" />
          Download Invoice
        </button>
      </div>

      {!showPreview ? (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Invoice Details */}
          <div className="glass-card rounded-2xl p-6 space-y-4">
            <h3 className="text-lg font-semibold text-white flex items-center gap-2">
              <FileText className="w-5 h-5 text-indigo-400" />
              Detail Invoice
            </h3>

            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="text-xs text-slate-400 mb-1 block">Invoice #</label>
                <input type="text" value={invoice.number} onChange={e => setInvoice({...invoice, number: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
              </div>
              <div>
                <label className="text-xs text-slate-400 mb-1 block">Tanggal</label>
                <input type="date" value={invoice.date} onChange={e => setInvoice({...invoice, date: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
              </div>
              <div>
                <label className="text-xs text-slate-400 mb-1 block">Jatuh Tempo</label>
                <input type="date" value={invoice.dueDate} onChange={e => setInvoice({...invoice, dueDate: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
              </div>
              <div>
                <label className="text-xs text-slate-400 mb-1 block">Mata Uang</label>
                <select value={invoice.currency} onChange={e => setInvoice({...invoice, currency: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none">
                  <option value="IDR">IDR (Rupiah)</option>
                  <option value="USD">USD (Dollar)</option>
                  <option value="EUR">EUR (Euro)</option>
                </select>
              </div>
            </div>

            <div className="border-t border-slate-700 pt-4">
              <h4 className="text-sm font-medium text-slate-300 mb-3">Dari (Anda)</h4>
              <div className="space-y-2">
                <input type="text" placeholder="Nama Bisnis/Anda" value={invoice.fromName} onChange={e => setInvoice({...invoice, fromName: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                <input type="email" placeholder="Email" value={invoice.fromEmail} onChange={e => setInvoice({...invoice, fromEmail: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                <textarea placeholder="Alamat" value={invoice.fromAddress} onChange={e => setInvoice({...invoice, fromAddress: e.target.value})} rows={2}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600 resize-none" />
              </div>
            </div>

            <div className="border-t border-slate-700 pt-4">
              <h4 className="text-sm font-medium text-slate-300 mb-3">Kepada (Klien)</h4>
              <div className="space-y-2">
                <input type="text" placeholder="Nama Klien/Perusahaan" value={invoice.toName} onChange={e => setInvoice({...invoice, toName: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                <input type="email" placeholder="Email Klien" value={invoice.toEmail} onChange={e => setInvoice({...invoice, toEmail: e.target.value})}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                <textarea placeholder="Alamat Klien" value={invoice.toAddress} onChange={e => setInvoice({...invoice, toAddress: e.target.value})} rows={2}
                  className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600 resize-none" />
              </div>
            </div>
          </div>

          {/* Items */}
          <div className="glass-card rounded-2xl p-6 space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-semibold text-white">Item Invoice</h3>
              <button onClick={addItem} className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-indigo-500/20 text-indigo-300 text-sm hover:bg-indigo-500/30 transition-all">
                <Plus className="w-4 h-4" /> Tambah
              </button>
            </div>

            <div className="space-y-3">
              {items.map((item, index) => (
                <div key={item.id} className="p-3 rounded-xl bg-slate-800/50 border border-slate-700/50 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="text-xs text-slate-500">Item #{index + 1}</span>
                    {items.length > 1 && (
                      <button onClick={() => removeItem(item.id)} className="text-red-400 hover:text-red-300">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    )}
                  </div>
                  <input type="text" placeholder="Deskripsi layanan/produk" value={item.description}
                    onChange={e => updateItem(item.id, 'description', e.target.value)}
                    className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600" />
                  <div className="grid grid-cols-2 gap-2">
                    <div>
                      <label className="text-xs text-slate-500">Qty</label>
                      <input type="number" min="1" value={item.quantity}
                        onChange={e => updateItem(item.id, 'quantity', parseInt(e.target.value) || 0)}
                        className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
                    </div>
                    <div>
                      <label className="text-xs text-slate-500">Harga</label>
                      <input type="number" min="0" value={item.price}
                        onChange={e => updateItem(item.id, 'price', parseInt(e.target.value) || 0)}
                        className="w-full px-3 py-2 rounded-lg bg-slate-900 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none" />
                    </div>
                  </div>
                  <p className="text-xs text-emerald-400 font-medium">Total: {formatCurrency(item.quantity * item.price)}</p>
                </div>
              ))}
            </div>

            {/* Totals */}
            <div className="border-t border-slate-700 pt-4 space-y-2">
              <div className="flex justify-between text-sm text-slate-400">
                <span>Subtotal</span>
                <span>{formatCurrency(subtotal)}</span>
              </div>
              <div className="flex justify-between text-sm text-slate-400">
                <span>PPN (11%)</span>
                <span>{formatCurrency(tax)}</span>
              </div>
              <div className="flex justify-between text-lg font-bold text-white pt-2 border-t border-slate-700">
                <span>Total</span>
                <span className="text-emerald-400">{formatCurrency(total)}</span>
              </div>
            </div>

            {/* Notes */}
            <div>
              <label className="text-xs text-slate-400 mb-1 block">Catatan</label>
              <textarea placeholder="Catatan tambahan untuk klien..." value={invoice.notes} onChange={e => setInvoice({...invoice, notes: e.target.value})} rows={3}
                className="w-full px-3 py-2 rounded-lg bg-slate-800 border border-slate-700 text-white text-sm focus:border-indigo-500 focus:outline-none placeholder:text-slate-600 resize-none" />
            </div>
          </div>
        </div>
      ) : (
        /* Preview */
        <div className="glass-card rounded-2xl p-8 max-w-3xl mx-auto">
          <div className="border-2 border-dashed border-slate-700 rounded-xl p-8">
            <div className="flex justify-between items-start mb-8">
              <div>
                <h2 className="text-2xl font-bold gradient-text">INVOICE</h2>
                <p className="text-slate-400 text-sm mt-1">#{invoice.number}</p>
              </div>
              <div className="text-right">
                <p className="text-sm text-slate-400">Tanggal: {invoice.date}</p>
                <p className="text-sm text-slate-400">Jatuh Tempo: {invoice.dueDate || '-'}</p>
              </div>
            </div>

            <div className="grid grid-cols-2 gap-8 mb-8">
              <div>
                <h4 className="text-xs text-slate-500 uppercase tracking-wider mb-2">Dari</h4>
                <p className="text-white font-medium">{invoice.fromName || 'Your Name'}</p>
                <p className="text-sm text-slate-400">{invoice.fromEmail}</p>
                <p className="text-sm text-slate-400">{invoice.fromAddress}</p>
              </div>
              <div>
                <h4 className="text-xs text-slate-500 uppercase tracking-wider mb-2">Kepada</h4>
                <p className="text-white font-medium">{invoice.toName || 'Client Name'}</p>
                <p className="text-sm text-slate-400">{invoice.toEmail}</p>
                <p className="text-sm text-slate-400">{invoice.toAddress}</p>
              </div>
            </div>

            <table className="w-full mb-8">
              <thead>
                <tr className="border-b border-slate-700">
                  <th className="text-left text-xs text-slate-500 py-2">DESKRIPSI</th>
                  <th className="text-center text-xs text-slate-500 py-2">QTY</th>
                  <th className="text-right text-xs text-slate-500 py-2">HARGA</th>
                  <th className="text-right text-xs text-slate-500 py-2">TOTAL</th>
                </tr>
              </thead>
              <tbody>
                {items.map(item => (
                  <tr key={item.id} className="border-b border-slate-800">
                    <td className="py-3 text-sm text-white">{item.description || '-'}</td>
                    <td className="py-3 text-sm text-slate-300 text-center">{item.quantity}</td>
                    <td className="py-3 text-sm text-slate-300 text-right">{formatCurrency(item.price)}</td>
                    <td className="py-3 text-sm text-white text-right font-medium">{formatCurrency(item.quantity * item.price)}</td>
                  </tr>
                ))}
              </tbody>
            </table>

            <div className="flex justify-end">
              <div className="w-64 space-y-2">
                <div className="flex justify-between text-sm text-slate-400">
                  <span>Subtotal</span>
                  <span>{formatCurrency(subtotal)}</span>
                </div>
                <div className="flex justify-between text-sm text-slate-400">
                  <span>PPN (11%)</span>
                  <span>{formatCurrency(tax)}</span>
                </div>
                <div className="flex justify-between text-lg font-bold text-white pt-2 border-t border-slate-700">
                  <span>Total</span>
                  <span className="text-emerald-400">{formatCurrency(total)}</span>
                </div>
              </div>
            </div>

            {invoice.notes && (
              <div className="mt-8 p-4 rounded-lg bg-slate-800/50">
                <p className="text-xs text-slate-500 mb-1">Catatan:</p>
                <p className="text-sm text-slate-300">{invoice.notes}</p>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
